export { calculatePayroll, calculateINSSEmployee, calculateIRRF } from './payroll'
export { calculateThirteenth, calculateMonthsWorked } from './thirteenth'
export { calculateVacation, getVacationDaysByAbsences, getPaymentDeadline } from './vacation'
export type { VacationInput, VacationBreakdown } from './vacation'
export { calculateTermination } from './termination'
export { CURRENT_TAX_TABLE, getTaxTable, TAX_TABLE_2026 } from './tax-tables'
export type { PayrollInput, PayrollBreakdown } from './payroll'
export type { ThirteenthInput, ThirteenthBreakdown } from './thirteenth'
export type { TerminationInput, TerminationBreakdown, TerminationType } from './termination'
export type { TaxTable, INSSBracket, IRRFBracket } from './tax-tables'
